# Generated by Django 4.2.5 on 2023-10-06 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('adviser_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('credits', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('prerequisites', models.TextField()),
                ('semester_offered', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('total_credits_required', models.IntegerField()),
                ('duration_in_years', models.IntegerField()),
                ('program_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DegreeRequirement',
            fields=[
                ('requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('credits_required', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.degreeprogram')),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField()),
                ('grade', models.CharField(max_length=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.student')),
            ],
        ),
    ]
