# Generated by Django 4.2.5 on 2023-10-10 17:25

from django.db import migrations

def populate_course(apps, schema_editor):
    Course = apps.get_model('degree_checklist', 'Course')

    course_to_insert = [
        Course(course_id=1105,course_code='CL1105', course_name='Computer Literacy', credits=3.00, description='Description for Computer Literacy', prerequisites='None', semester_offered='Fall'),
        Course(course_id=1301,course_code='IS1301', course_name='Introduction to Information Science', credits=3.00, description='Description for Introduction to Information Science', prerequisites='None', semester_offered='Spring'),
        Course(course_id=1315,course_code='PF1315', course_name='Programming Fundamentals', credits=3.00, description='Description for Programming Fundamentals', prerequisites='None', semester_offered='Spring'),
        Course(course_id=2315,course_code='PBA2315', course_name='Programming Business Applications', credits=3.00, description='Description for Programming Business Applications', prerequisites='PF1315', semester_offered='Fall'),
        Course(course_id=2342,course_code='SBE2342', course_name='Statistics for Business and Economics', credits=4.00, description='Description for Statistics for Business and Economics', prerequisites='None', semester_offered='Spring'),
        Course(course_id=2345,course_code='VGD2345', course_name='Video Game Design', credits=3.00, description='Description for Video Game Design', prerequisites='None', semester_offered='Spring'),
        Course(course_id=2390,course_code='SAD2390', course_name='Systems Analysis and Design', credits=4.00, description='Description for Systems Analysis and Design', prerequisites='None', semester_offered='Summer'),
        Course(course_id=3310,course_code='SAB3310', course_name='Spreadsheet Applications in Business', credits=3.00, description='Description for Spreadsheet Applications in Business', prerequisites='None', semester_offered='Fall'),
        Course(course_id=3312,course_code='ABP3312', course_name='Advanced Business Programming', credits=3.00, description='Description for Advanced Business Programming', prerequisites='PBA2315', semester_offered='Spring'),
        Course(course_id=3320,course_code='DCC3320', course_name='Digital Communications and Collaboration', credits=3.00, description='Description for Digital Communications and Collaboration', prerequisites='None', semester_offered='Fall'),
        Course(course_id=3330,course_code='MIS3330', course_name='Management Information Systems', credits=3.00, description='Description for Management Information Systems', prerequisites='None', semester_offered='Spring'),
        Course(course_id=3342,course_code='PBI3342', course_name='Principles of Business Informatics', credits=3.00, description='Description for Principles of Business Informatics', prerequisites='None', semester_offered='Summer'),
        Course(course_id=3345,course_code='VGDII3345', course_name='Video Game Design II', credits=3.00, description='Description for Video Game Design II', prerequisites='VGD2345', semester_offered='Fall'),
        Course(course_id=3350,course_code='DSD3350', course_name='Database Systems Design', credits=4.00, description='Description for Database Systems Design', prerequisites='None', semester_offered='Spring'),
        Course(course_id=3372,course_code='WAD3372', course_name='Web Application Development', credits=3.00, description='Description for Web Application Development', prerequisites='None', semester_offered='Spring'),
        Course(course_id=3380,course_code='IS3380', course_name='Information Security', credits=3.00, description='Description for Information Security', prerequisites='None', semester_offered='Fall'),
        Course(course_id=3382,course_code='EWAD3382', course_name='Enterprise Web-Based Applications Development', credits=3.00, description='Description for Enterprise Web-Based Applications Development', prerequisites='WAD3372', semester_offered='Spring'),
        Course(course_id=3385,course_code='NDC3385', course_name='Networking and Data Communications', credits=3.00, description='Description for Networking and Data Communications', prerequisites='None', semester_offered='Fall'),
        Course(course_id=3390,course_code='PM3390', course_name='Project Management', credits=3.00, description='Description for Project Management', prerequisites='None', semester_offered='Spring'),
        Course(course_id=4096,course_code='SRIS4096', course_name='Supervised Reading in Information Systems', credits=2.00, description='Description for Supervised Reading in Information Systems', prerequisites='None', semester_offered='Summer'),
        Course(course_id=4310,course_code='BIDSS4310', course_name='Business Intelligence and Decision Support Systems', credits=3.00, description='Description for Business Intelligence and Decision Support Systems', prerequisites='None', semester_offered='Fall'),
        Course(course_id=4325,course_code='PGIS4325', course_name='Principles of Geographic Information Systems', credits=3.00, description='Description for Principles of Geographic Information Systems', prerequisites='None', semester_offered='Spring'),
        Course(course_id=4331,course_code='POM4331', course_name='Production and Operations Management', credits=3.00, description='Description for Production and Operations Management', prerequisites='None', semester_offered='Summer'),
        Course(course_id=4343,course_code='SCM4343', course_name='Supply Chain Management', credits=3.00, description='Description for Supply Chain Management', prerequisites='None', semester_offered='Fall'),
        Course(course_id=4350,course_code='DMM4350', course_name='Data Mining Methods', credits=3.00, description='Description for Data Mining Methods', prerequisites='None', semester_offered='Spring'),
        Course(course_id=4352,course_code='BF4352', course_name='Business Forecasting', credits=3.00, description='Description for Business Forecasting', prerequisites='None', semester_offered='Summer'),
        Course(course_id=4358,course_code='ORM4358', course_name='Operations Research Methods', credits=3.00, description='Description for Operations Research Methods', prerequisites='None', semester_offered='Fall'),
        Course(course_id=4360,course_code='OOAD4360', course_name='Object-Oriented Analysis and Design', credits=3.00, description='Description for Object-Oriented Analysis and Design', prerequisites='None', semester_offered='Spring'),
        Course(course_id=4364,course_code='IQEF4364', course_name='Introduction to Quantitative Economics and Finance', credits=3.00, description='Description for Introduction to Quantitative Economics and Finance', prerequisites='None', semester_offered='Summer'),
        Course(course_id=4370,course_code='HIE4370', course_name='Health Informatics and E-Medicine', credits=3.00, description='Description for Health Informatics and E-Medicine', prerequisites='None', semester_offered='Fall'),
        Course(course_id=4372,course_code='IVIZ4372', course_name='Information Visualization', credits=3.00, description='Description for Information Visualization', prerequisites='None', semester_offered='Spring'),
        Course(course_id=4382,course_code='SDDB4382', course_name='Software Development in a Database Environment', credits=3.00, description='Description for Software Development in a Database Environment', prerequisites='None', semester_offered='Summer'),
        Course(course_id=4385,course_code='MAD4385', course_name='Mobile Application Development', credits=3.00, description='Description for Mobile Application Development', prerequisites='None', semester_offered='Fall'),
        Course(course_id=4390,course_code='SSD4390', course_name='Software Systems Development', credits=3.00, description='Description for Software Systems Development', prerequisites='None', semester_offered='Spring'),
        Course(course_id=4392,course_code='APCIS4392', course_name='Applied Problems in Computer and Information Systems', credits=3.00, description='Description for Applied Problems in Computer and Information Systems', prerequisites='None', semester_offered='Summer'),
        Course(course_id=4410,course_code='APCIS4393', course_name='Advanced Studies in Information Systems', credits=3.00, description='Description for Advanced Studies in Information Systems', prerequisites='None', semester_offered='Summer'),
        Course(course_id=4425,course_code='ISPROJ4394', course_name='Information Systems Project', credits=4.00, description='Description for Information Systems Project', prerequisites='APCIS4392', semester_offered='Fall'),
        Course(course_id=4435,course_code='DLSYS4395', course_name='Distributed Systems', credits=3.00, description='Description for Distributed Systems', prerequisites='None', semester_offered='Spring'),
        Course(course_id=4445,course_code='WAPDEV4396', course_name='Web Application Development II', credits=3.00, description='Description for Web Application Development II', prerequisites='WAPDEV3372', semester_offered='Summer'),
        Course(course_id=4456,course_code='ISRES4397', course_name='Independent Research in Information Systems', credits=3.00, description='Description for Independent Research in Information Systems', prerequisites='Permission of instructor', semester_offered='Fall'),
        Course(course_id=4465,course_code='DBMGT4398', course_name='Database Management Systems II', credits=3.00, description='Description for Database Management Systems II', prerequisites='DBSYS3350', semester_offered='Spring'),
        Course(course_id=4475,course_code='CAPIS4399', course_name='Capstone in Information Systems', credits=4.00, description='Description for Capstone in Information Systems', prerequisites='Senior Standing', semester_offered='Summer'),
    ]
 

       

    Course.objects.bulk_create(course_to_insert)
    

class Migration(migrations.Migration):

    dependencies = [
        ('degree_checklist', '0001_initial'),
    ]

    operations = [
       migrations.RunPython(populate_course)
    ]