# Generated by Django 4.2.5 on 2023-10-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree_checklist', '0002_auto_20231010_2132'),
        ('degree_checklist', '0002_courseenrollment_semester'),
    ]

    operations = [
    ]
